version: "3.7"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # command: ["php", "artisan", "serve", "--host", "0.0.0.0"]
    depends_on:
      - db
    environment:
      LOG_CHANNEL: ${LOG_CHANNEL:-"errorlog"}
      APP_NAME: ${APP_NAME:-Laravel}
      APP_ENV: ${APP_ENV:-local}
      APP_KEY: ${APP_KEY:-"base64:0RZzJqqCHu8+tBNz955FHVze/Mx/NpLz/tgTesTOOTE:"}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8000}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-m150lb-b}
      DB_USERNAME: ${DB_USERNAME:-app}
      DB_PASSWORD: ${DB_PASSWORD:-app}
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
      MYSQL_DATABASE: "m150lb-b"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: db

    restart: always
    ports:
      - 8080:80

volumes:
  db_data:
